### ISSUE TITLE
Can CoPilot and TigerGraph Database run on the same Machine???

### ISSUE THREAD

**Issue by demit733** [tigergraph/CoPilot#273]
I stared my Docker instance of TigerGraph database, then I started my Docker instance of CoPilot on the same computer. It seems that TigerGraph and CoPilot cannot exist on the same machine because of port conflicts (Port 9000 used by both TIgerGraph & milvus-minio).  Is there any documentation talking about how the two systems can coexist at runtime?

**Comment by RobRossmiller-TG** [comment]
No, since that's not unique to our tool. Please follow the [getting started](https://docs.tigergraph.com/tg-copilot/current/getstarted/self-managed#_4_start_copilot) documentation. We have everything configured via docker-compose.

Closing this issue since I was just able to run the main branch without issue. If you have any follow-up questions, please continue to use this thread or post on our [community forum](https://dev.tigergraph.com/forum/)
